[pytest]
asyncio_mode=auto
testpaths = tests/unit
python_files = test_*.py [0-9]_*.py
addopts = -vvv --cov=core_client --cov-report=term-missing
markers =
    integration: requires a running core instance
