from enum import Enum


class MetricsMonitorName(str, Enum):
    cpu_ncpu = "cpu_ncpu"
    cpu_system = "cpu_system"
    cpu_user = "cpu_user"
    cpu_idle = "cpu_idle"
    cpu_other = "cpu_other"
    disk_total = "disk_total"
    disk_usage = "disk_usage"
    ffmpeg_process = "ffmpeg_process"
    filesystem_limit = "filesystem_limit"
    filesystem_usage = "filesystem_usage"
    filesystem_files = "filesystem_files"
    mem_total = "mem_total"
    mem_free = "mem_free"
    net_rx = "net_rx"
    net_tx = "net_tx"
    restream_process = "restream_process"
    restream_process_states = "restream_process_states"
    restream_io = "restream_io"
    restream_state = "restream_state"
    session_total = "session_total"
    session_limit = "session_limit"
    session_active = "session_active"
    session_rxbytes = "session_rxbytes"
    session_txbytes = "session_txbytes"
    session_rxbitrate = "session_rxbitrate"
    session_txbitrate = "session_txbitrate"
    session_maxtxbitrate = "session_maxtxbitrate"
    session_maxrxbitrate = "session_maxrxbitrate"
    uptime_uptime = "uptime_uptime"
